# Generated by Django 3.0.2 on 2020-02-03 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_suggestions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suggestions',
            new_name='Suggestion',
        ),
    ]
